package com.santanna.olympicgames.domain.enums;

public enum Country {
    UNITED_STATES, CHINA, JAPAN, GREAT_BRITAIN, TAIWAN, RUSSIA, AUSTRALIA, NETHERLANDS, FRANCE, GERMANY, ITALY, CANADA,
    BRAZIL, NEW_ZEALAND, SOUTH_KOREA, CUBA, HUNGARY, POLAND, CZECH_REPUBLIC, KENYA, SPAIN, SWITZERLAND, JAMAICA, SWEDEN,
    BELGIUM, DENMARK, NORWAY, CROATIA, AUSTRIA, SOUTH_AFRICA, UKRAINE, TURKEY, IRAN, GREECE, BELARUS, SERBIA, GEORGIA,
    AZERBAIJAN, UZBEKISTAN, INDONESIA, ISRAEL, THAILAND, BAHRAIN, KAZAKHSTAN, SLOVENIA, ROMANIA, ARGENTINA, VENEZUELA,
    EGYPT, PHILIPPINES, BULGARIA, SLOVAKIA, LITHUANIA, ESTONIA, TUNISIA, MEXICO, NIGERIA, PORTUGAL, KOSOVO, FIJI, QATAR,
    ICELAND, MALAYSIA, INDIA, IRELAND, HONG_KONG, GHANA, GUADELOUPE, BERMUDA, KUWAIT, JORDAN, DOMINICAN_REPUBLIC,
    CAMEROON, LATVIA, PUERTO_RICO, TRINIDAD_AND_TOBAGO, SAUDI_ARABIA, VIETNAM, NAMIBIA, MONGOLIA, BANGLADESH, TAJIKISTAN,
    MONTENEGRO, MAURITIUS, MYANMAR, PANAMA, MAURITANIA, NEPAL, SYRIA, SENEGAL, LIBYA, ESWATINI, ZAMBIA, ARUBA, ERITREA,
    AFGHANISTAN, ANDORRA, ANGUILLA, BENIN, BOTSWANA, BURUNDI, CENTRAL_AFRICAN_REPUBLIC,  COMOROS, CAPE_VERDE,
    CAYMAN_ISLANDS, DJIBOUTI, DOMINICA, GUINEA, GUINEA_BISSAU, GAMBIA, GRENADA, GREENLAND, GUYANA, HAITI, BRUNEI,
    LESOTHO, LAOS, LEBANON, LIECHTENSTEIN, LIBERIA, MALAWI, MALDIVES, MALI, MALTA, MAYOTTE, MARTINIQUE, MONTSERRAT,
    NICARAGUA, NIGER, NORFOLK_ISLAND, NAURU, OMAN, PALAU, PAPUA_NEW_GUINEA, SEYCHELLES, SOLOMON_ISLANDS, SAMOA, SURINAME,
    SWAZILAND, SOMALIA, SUDAN, SIERRA_LEONE, TURKMENISTAN, TIMOR_LESTE,VIRGIN_ISLANDS, YEMEN, ZIMBABWE;
}
