package com.santanna.olympicgames.domain.enums;

public enum Sport {
    ARCHERY, ATHLETICS, BADMINTON, BASEBALL, BASKETBALL, BEACH_VOLLEYBALL, BOXING, CANOE , CYCLING,
    DIVING, EQUESTRIAN, FENCING, FOOTBALL, GOLF, GYMNASTICS_ARTISTIC, GYMNASTICS_RHYTHMIC, HANDBALL, HOCKEY, JUDO,
    KARATE, MARATHON , PENTATHLON, ROWING, RUGBY, SAILING, SHOOTING, SKATEBOARDING, SOCCER, SOFTBALL, SPORT_CLIMBING,
    SURFING, SWIMMING, TABLE_TENNIS, TAEKWONDO, TENNIS, GYMNASTICS, TRIATHLON, VOLLEYBALL, WATER_POLO, WEIGHTLIFTING, WRESTLING;
    }
